### ISSUE TITLE
SDKを使わずに認証APIを叩く

### ISSUE THREAD

**Issue by kajirikajiri** [OnetapInc/locked-rails-web-sample#15]
https://onetapinc.slack.com/archives/CBZQU5H6U/p1566955789000600

1|2
-|-
![image](https://user-images.githubusercontent.com/37785038/63820080-e798e800-c982-11e9-83dd-967384b16b44.png)|![image](https://user-images.githubusercontent.com/37785038/63820089-eebff600-c982-11e9-99bc-dd64475bf3c8.png)

**Comment by kazukinakamuraKN** [comment]
@goleador0322 今朝の話をissueにしましたが、これは９月１３日〆ですか？
そして、SDKという言葉の示す範囲はとても広いです。
どれをさしますか？

**Comment by gumpen** [comment]
こちらのリポジトリ&PRで対応
